security:
  basic.enabled: false

spring:
  profiles.active: default

server:
  port: 8090

---
spring:
  profiles: default
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL
    schema: classpath:/schema.sql
---
spring:
  profiles: heroku
  datasource:
    url: ${JDBC_DATABASE_URL}
    driverClassName: org.postgresql.Driver
    maxActive: 10
    maxIdle: 5
    minIdle: 2
    initialSize: 5
    removeAbandoned: true